### PR TITLE
fix(postcss): correct windows paths for webpack

### LINKED ISSUE #1888: Windows: HMR doesn't work for a fresh Next.js project
### Description

Creating a fresh Next.js with PandaCSS:
1. I receive a warning on compilation. It may be Windows only. There is a separate issue: #1783.
2. Styles don't recompile. So I have to reboot the dev server every time I change styles.

### Link to Reproduction

Windows only?

### Steps to reproduce

1. Install via https://panda-css.com/docs/installation/nextjs
2. `pnpm dev`
3. Go to localhost:3000
4. Receive the following warning:
```
> next dev

   ▲ Next.js 14.0.4
   - Local:        http://localhost:3000

 ✓ Ready in 4.2s
 ○ Compiling / ...
🐼 info [hrtime] Extracted in (8.99ms)
 ⚠ ./app/globals.css.webpack[javascript/auto]!=!./node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[11].oneOf[12].use[2]!./node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[11].oneOf[12].use[3]!./app/globals.css
Invalid dependencies have been reported by plugins or loaders for this module. All reported dependencies need to be absolute paths.
Invalid dependencies may lead to broken watching and caching.
As best effort we try to convert all invalid values to absolute paths and converting globs into context dependencies, but this is deprecated behavior.
Loaders: Pass absolute paths to this.addDependency (existing files), this.addMissingDependency (not existing files), and this.addContextDependency (directories).
Plugins: Pass absolute paths to fileDependencies (existing files), missingDependencies (not existing files), and contextDependencies (directories).
Globs: They are not supported. Pass absolute path to the directory as context dependencies.
The following invalid values have been reported:
 * "C:/Users/boris/Projects/panda-nextjs/app"
 * "C:/Users/boris/Projects/panda-nextjs/node_modules/.pnpm/@pandacss+dev@0.23.0_typescript@5.3.3/node_modules/@pandacss/dev/dist/index.mjs"
 * "C:/Users/boris/Projects/panda-nextjs/pages"
 * and more ...

Import trace for requested module:
./app/globals.css.webpack[javascript/auto]!=!./node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[11].oneOf[12].use[2]!./node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[11].oneOf[12].use[3]!./app/globals.css
./app/globals.css
 ⚠ ./app/globals.css.webpack[javascript/auto]!=!./node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[11].oneOf[12].use[2]!./node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[11].oneOf[12].use[3]!./app/globals.css
Invalid dependencies have been reported by plugins or loaders for this module. All reported dependencies need to be absolute paths.
Invalid dependencies may lead to broken watching and caching.
As best effort we try to convert all invalid values to absolute paths and converting globs into context dependencies, but this is deprecated behavior.
Loaders: Pass absolute paths to this.addDependency (existing files), this.addMissingDependency (not existing files), and this.addContextDependency (directories).
Plugins: Pass absolute paths to fileDependencies (existing files), missingDependencies (not existing files), and contextDependencies (directories).
Globs: They are not supported. Pass absolute path to the directory as context dependencies.
The following invalid values have been reported:
 * "C:/Users/boris/Projects/panda-nextjs/app"
 * "C:/Users/boris/Projects/panda-nextjs/node_modules/.pnpm/@pandacss+dev@0.23.0_typescript@5.3.3/node_modules/@pandacss/dev/dist/index.mjs"
 * "C:/Users/boris/Projects/panda-nextjs/pages"
 * and more ...
```
5. Also, go to `page.tsx`:
```tsx
import { css } from '@/styled-system/css'

export default function Home() {
  return (
    <main className={css({bg: 'red'})}>Hello</main>
  )
}
```
6. Change `red` to `green`.
7. Panda still bundles the old color `red`. Since `green` wasn't bundled, the background is now white.
8. To make it work, I have to `pnpm dev` again.

### JS Framework

React (TS)

### Panda CSS Version

0.23.0

### Browser

N/A

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by mewdriller**
Closes #1888 

## 📝 Description

Update dependency paths on Windows before they're passed to `postcss-loader` so that they're marked as valid dependencies within `webpack`.

## ⛳️ Current behavior (updates)

The `Builder` and other internals in `@pandacss/node` use the `pathe` package to generate paths that are more Windows-friendly for other use cases. However, those Windows-friendly paths are rejected by `webpack` as invalid absolute paths as they use forward slash instead of backlash. Both types are valid on Windows, but `webpack` only accepts backslash.

## 🚀 New behavior

Before we pass descriptions of dependencies to `postcss-loader` (and therefore `webpack`) we adjust the paths if the process is running on  the `win32` platform so that `webpack` will accept them.

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

I didn't want to replace other usages of Windows-friendly paths that are coming from `pathe` in case there's a good reason for that in non-`webpack` related flows.

### CODE REVIEW

File: packages/postcss/src/index.ts [hunk 1]
```diff
@@ -48,6 +49,14 @@ export const pandacss: PluginCreator<{ configPath?: string; cwd?: string }> = (o
...
 
         builder.registerDependency((dep) => {
+          if (process.platform === 'win32') {
+            WIN32_NORMALIZED_DEP_KEYS.forEach((key) => {
+              if (typeof dep[key] === 'string') {
+                dep[key] = path.normalize(dep[key])
+              }
+            })
+          }
+
```
Comment (astahmer) [inline packages/postcss/src/index.ts:59]: got it, thank your for looking into this issue, this helps a lot !

since this change will affect every windows users (e.g, not just those using webpack), I'm wondering if that will break anything for vite/astro users ? would appreciate if you could check it using the `sandbox` folder

if there's no issue, this PR looks good to me 🙏

Comment (mewdriller) [reply packages/postcss/src/index.ts:59]: Good call! Here's a look at the `vite-ts` and `astro` setups in the `sandbox` folder:

# `astro`

✅ Tested initial compilation and HMR changes after altering `src/components/button.tsx`.

image
image

# `vite-ts`

✅ Tested initial compilation and HMR changes after altering `src/App.tsx`.

image
image
image

Comment (astahmer) [reply packages/postcss/src/index.ts:59]: nice ! could you also try updating the config with the dev command running ? could be anything that will trigger a codegen again, e.g add/update/delete a recipe or token, utility, conditions, etc

this is most likely the scenario that *could* break, hopefully it's still fine

Comment (mewdriller) [reply packages/postcss/src/index.ts:59]: Sure thing; here's the output when making changes to the `panda.config.ts` file while the `pnpm run dev` script is running:

# `astro`

✅ Tested configuration changes by flipping the `preflight` value from `true` to `false` and back. The visuals changed correctly and the terminal output looked correct as well.

image
image
image

# `vite-ts`

✅ Tested configuration changes by flipping the `preflight` value from `true` to `false` and back. The visuals changed correctly and the terminal output looked correct as well.

image
image
image
image
image

Comment (mewdriller) [reply packages/postcss/src/index.ts:59]: Let me know if there's a best test for the `panda.config.ts` file watching / generation. I was trying to find something across both projects that _only_ required a change in that file so the config watching was isolated (and not piggybacking off source file changes).

Comment (astahmer) [reply packages/postcss/src/index.ts:59]: `preflight` won't change the `outdir` (styled-system) generation, this is what I meant by `codegen` step, sorry if I wasn't clear, it will only re-trigger a CSS generation

basically I'm looking to see if anything will break after a config reload + outdir generated again (only happens in [those cases](https://github.com/chakra-ui/panda/blob/main/packages/config/src/config-deps.ts#L21-L39)

Comment (mewdriller) [reply packages/postcss/src/index.ts:59]: You were perfectly clear, I just failed at basic reading comprehension. 😅

# `astro`

✅ Tested by adding a recipe via `defineRecipe`, adding a recipe inline in `theme.recipes`, and adding the `groupHover` condition shown in the [docs](https://panda-css.com/docs/customization/conditions#creating-a-condition).

```ts
// sandbox\astro\panda.config.ts
import { defineConfig, defineRecipe } from '@pandacss/dev'

const definedRecipe = defineRecipe({
  className: 'defined-recipe',
  defaultVariants: { color: 'default' },
  variants: {
    color: {
      default: { backgroundColor: 'orange.900', color: 'black' },
      primary: { backgroundColor: 'rebeccapurple', color: 'white' },
    },
  },
})

export default defineConfig({
  preflight: true,
  include: ['./src/**/*.{astro,tsx}'],
  outdir: 'styled-system',
  conditions: {
    groupHover: '[role=group]:where(:hover, [data-hover]) &',
  },
  theme: {
    recipes: {
      definedRecipe,
      inlineRecipe: {
        className: 'inline-recipe',
        defaultVariants: { size: 'default' },
        variants: {
          size: {
            default: { fontSize: '32px' },
            sm: { fontSize: '16px' },
            lg: { fontSize: '48px' },
          },
        },
      },
    },
  },
})
```
image

# `vite-ts`

✅ Tested by adding a recipe via `defineRecipe`, adding a recipe inline in `theme.recipes`, and adding the `groupHover` condition shown in the [docs](https://panda-css.com/docs/customization/conditions#creating-a-condition).

```ts
// sandbox\vite-ts\panda.config.ts
import { defineConfig, defineRecipe } from '@pandacss/dev'

const someRecipe = defineRecipe({
  className: 'some-recipe',
  base: { color: 'green', fontSize: '16px' },
  variants: {
    size: { small: { fontSize: '14px' } },
  },
  compoundVariants: [{ size: 'small', css: { color: 'blue' } }],
})

const definedRecipe = defineRecipe({
  className: 'defined-recipe',
  defaultVariants: { color: 'default' },
  variants: {
    color: {
      default: { backgroundColor: 'orange.900', color: 'black' },
      primary: { backgroundColor: 'rebeccapurple', color: 'white' },
    },
  },
})

export default defineConfig({
  preflight: true,
  include: ['./src/**/*.{tsx,jsx}', './pages/**/*.{jsx,tsx}'],
  exclude: [],
  outdir: 'styled-system',
  jsxFactory: 'panda',
  jsxFramework: 'react',
  conditions: {
    groupHover: '[role=group]:where(:hover, [data-hover]) &',
  },
  theme: {
    semanticTokens: {
      colors: {
        text: { value: { base: '{colors.gray.600}', _osDark: '{colors.gray.400}' } },
      },
    },
    recipes: {
      definedRecipe,
      inlineRecipe: {
        className: 'inline-recipe',
        defaultVariants: { size: 'default' },
        variants: {
          size: {
            default: { fontSize: '32px' },
            sm: { fontSize: '16px' },
            lg: { fontSize: '48px' },
          },
        },
      },
      someRecipe,
      button: {
        className: 'button',
        jsx: ['Button', 'ListedButton', /WithRegex$/, 'PrimaryButtonLike'],
        description: 'A button styles',
        base: {
          fontSize: 'lg',
        },
        variants: {
          size: {
            sm: {
              padding: '2',
              borderRadius: 'sm',
            },
            md: {
              padding: '4',
              borderRadius: 'md',
            },
          },
          variant: {
            primary: {
              color: 'white',
              backgroundColor: 'blue.500',
            },
            danger: {
              color: 'white',
              backgroundColor: 'red.500',
            },
            secondary: {
              color: 'pink.300',
              backgroundColor: 'green.500',
            },
            purple: {
              color: 'amber.300',
              backgroundColor: 'purple.500',
            },
          },
          state: {
            focused: {
              color: 'green',
            },
            hovered: {
              color: 'pink.400',
            },
          },
          rounded: {
            true: {
              borderRadius: 'md',
            },
          },
        },
        compoundVariants: [
          {
            size: 'sm',
            variant: 'primary',
            css: {
              fontSize: '12px',
            },
          },
          {
            variant: ['primary', 'danger'],
            state: 'focused',
            css: {
              padding: 4,
              fontWeight: 'bold',
              fontSize: '24px',
            },
          },
        ],
      },
    },
  },
  globalCss: {
    '*': {
      fontFamily: 'Inter',
      margin: '0',
    },
    a: {
      color: 'inherit',
      textDecoration: 'none',
    },
  },
})
```

image
image

Comment (astahmer) [reply packages/postcss/src/index.ts:59]: awesome ! thank you for bearing with me and solving this issue 🙌

Comment (mewdriller) [reply packages/postcss/src/index.ts:59]: I noticed that in the `vite-ts` terminal output it didn't have similar output to the `astro` terminal RE outputting/changing files in the `styled-system` directory. I'm _assuming_ that's because the `vite-ts` dev-server clears previous terminal lines after it recompiles.

I did confirm that the `inlineRecipe` and `definedRecipe` show up in the autocomplete for imports from `../styled-system/recipes` and the condition seems to work as expected.

Comment (mewdriller) [reply packages/postcss/src/index.ts:59]: I just noticed the unit tests I added don't appear to working properly in the GitHub action, and there's also a `prettier` violation. I have to step away for a few hours but I'll focus on those changes when I get back.

If you'd rather take things yourself, feel free. Don't let me get in the way. 😅

**Comment by segunadebayo** [comment]
Thanks for helping with this @mewdriller. I tested it with my Windows tablet, and it works.

I believe it's safe to normalize paths across all postcss boundaries (in Builder#registerDependency and parseDependency function)

Updating them to include something like `normalize(resolve(file))` should work consistently across all platforms.

If it's okay, I'll update the code with these changes tomorrow.

**Comment by mewdriller** [comment]
> Thanks for helping with this @mewdriller. I tested it with my Windows tablet, and it works.
> 
> I believe it's safe to normalize paths across all postcss boundaries (in Builder#registerDependency and parseDependency function)
> 
> Updating them to include something like `normalize(resolve(file))` should work consistently across all platforms.
> 
> If it's okay, I'll update the code with these changes tomorrow.

Please do! I hesitated to do any more than I was *sure* about since I'm not very familiar with the codebase and why `pathe` was introduced. Let me know if there's anything more I can do to help, but I'm fine to get out of your way if that's better. 😅

File: packages/node/src/builder.ts [hunk 2]
```diff
@@ -3,7 +3,7 @@ import { optimizeCss } from '@pandacss/core'
 import { ConfigNotFoundError } from '@pandacss/error'
 import { logger } from '@pandacss/logger'
 import { existsSync, statSync } from 'fs'
-import { resolve } from 'pathe'
+import { normalize, resolve } from 'pathe'
```
Comment (mewdriller) [inline packages/node/src/builder.ts:6]: @segunadebayo (cc: @astahmer): Sorry to have communicated poorly previously. There's still the same issue with Windows HMR in the new release (`v0.27.1`) because `pathe.normalize` doesn't swap forward slash to backslash in Windows paths like `path.normalize` does.

That results in paths that still look like `C:/Users/test/Documents/panda-css-app/app` (forward slash) instead of `C:\\Users\\test\\Documents\\panda-css-app\\app` (backslash). Since `webpack` will reject the forward slash version, we still get the same HMR issue in Windows.

If we use the `node:path` version of `normalize` we should get the behavior we're looking. To my knowledge, in the parts of the code that deal with generating descriptions of `postcss` (and by extension `webpack`) dependencies, we don't need to / want to use `pathe` as it leads to the wrong path normalization.

There may be reasons you want/need `pathe` in other parts of the code (maybe the CLI generator?) but at the boundary with `postcss`/`webpack` it actually hurts us.

Sorry that wasn't clear from my previous comments / commits!

Comment (segunadebayo) [reply packages/node/src/builder.ts:6]: @mewdriller I agree.

Switched `pathe` to `node:path` here #2012
